import Head from "next/head";
import styles from "../styles/Home.module.css";
import Carousel from "../src/components/carrusel/Carousel";
import LayoutWrapper from "../components/LayoutWrapper";
import Codemirror from "../src/components/codemirror/Codemirror";
import React, { useState } from "react";
import { sample } from "../src/components/codemirror/components";

export default function Home() {
  const [language, changeLanguage] = useState("jsx");
  const [CarruselCode, SetCarruselCode] = useState(sample["carrusel"]);

  return (
    <div className={styles.container}>
      <Head>
        <title>JOSE REACT COMPONENTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutWrapper></LayoutWrapper>

      <main className="max-w-6xl mx-auto py-24">
        <Carousel  />

        <details className="w-full mt-10   font-semibold text-white hover:text-black cursor-pointer hover:bg-gray-100 bg-[#7843E6] rounded-lg ring-1 ring-[#7843E6]">
          <summary className="px-4 py-6">Click aquí para ver el código del componente</summary>
          <div className="px-4 py-6 pt-0 -mt-4">
            <Codemirror language={language} CarruselCode={CarruselCode} />
          </div>
        </details>
      </main>

      <footer className={styles.footer}>
        <p>
          Powered by <strong>JoseOrdaz</strong>
        </p>
      </footer>
    </div>
  );
}
