import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Carousel from "../src/components/carrusel/Carousel"
import LayoutWrapper from '../components/LayoutWrapper'


export default function Home() {

  const mockImagenes = [
		'./foto.jpg',
		'./foto1.jpg',
		'./foto2.jpg',
	];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutWrapper></LayoutWrapper>

      <main className={styles.main}>
   

        <div style={{ maxWidth: 1200, marginLeft: 'auto', marginRight: 'auto', marginTop: 64 }}>
   
        <Carousel imagenes={mockImagenes} />
   
   
        </div>

      </main>

      <footer className={styles.footer}>
       
         <p>Powered by <strong>JoseOrdaz</strong></p>
         
      
      </footer>
    </div>
  )
}
