import Head from "next/head";
import styles from "../styles/Home.module.css";
import Carousel from "../src/components/carrusel/Carousel";
import LayoutWrapper from "../components/LayoutWrapper";
import { Code } from "@nextui-org/react";
import Codemirror from "../src/components/codemirror/Codemirror";

export default function Home() {
  const mockImagenes = ["/foto.jpg", "/foto1.jpg", "/foto2.jpg"];

  return (
    <div className={styles.container}>
      <Head>
        <title>JOSE REACT COMPONENTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutWrapper></LayoutWrapper>

      <main className="max-w-4xl mx-auto py-24">
          <Carousel imagenes={mockImagenes} />
          <Codemirror />
      </main>

      <footer className={styles.footer}>
        <p>
          Powered by <strong>JoseOrdaz</strong>
        </p>
      </footer>
    </div>
  );
}
